<!DOCTYPE html>
<html>
    <head>
    <title><?=$this->content['title']?></title>
    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=8;FF=3;OtherUA=4" />

    <style>
        body {
	        background: #EEE;
        	font-family: Arial, Helvetica, sans-serif;
        	margin: 50px 0 0 0;
        	color: #333;
       
        }
        
        a, a:link, a:visited, a:active {
            color: #1EB6FF;
            text-decoration: none;
        }
        .container {
        	background: #fff;
        	padding: 25px;
        	width: 700px;
        	margin: 0 auto;
		  border: 1px solid #ddd;
		  -webkit-border-radius: 6px;
		   -moz-border-radius: 6px;
		          border-radius: 6px;
		  -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.075);
		     -moz-box-shadow: 0 1px 2px rgba(0,0,0,.075);
		          box-shadow: 0 1px 2px rgba(0,0,0,.075);
        }
        
        .container h1 {
	        font-size: 38px;
            padding: 0;
            margin: 0;
        }

        .container p {
        	font-size: 14px;
	        line-height: 22px;
        }
    </style>

</head>
<body>
    <div class="container">
        <?=$this->content['message']?>
    <div>
        <a href="#" onclick="javascript:history.go(-1);return false;">Back</a>
    </div>
    </div>
</body>
</html>